# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 862772729dd605384ae5787e10e581d3d112fc7c53edfc68581db200edf6672c699db2b67fa52abe87bcd6d7137a28eb17e6310676bcfe1ac5700bbf4123f330

test:
  secret_key_base: 138878954542c63ea658a93d845d829886df249f481b705190428cfad8d6651567b2cdea388f2742afe0f8031668144992072effe6ab812da9bcdac8b5dec6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
